@startuml
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Component.puml

LAYOUT_TOP_DOWN


Person(person,"Customer/Employee")

System_Boundary(c1, "Modular monolith boundary") {

Component(movies,"Movies","Facade/REST","Module responsible for managing the movie catalog")
Component(special,"Special offer","Facade/REST","Module responsible for managing the special offer")
Component(review,"Reviews","Facade/REST","Module responsible for managing user comments and reviews")
Component(reservations,"Reservations","Facade/REST","Module responsible for managing reservations")
Component(rentals,"Rentals","Facade/REST","Module responsible for managing rental list ")
Component(points,"Points","Facade/REST","Module responsible for maanaging bonus points")

ContainerDb(database, "NoSQL Database", "NoSQL Database", "Stores movies,rentals etc.")

Rel(person,movies,"show/create/remove movies")


Rel(movies,special,"mark/unmark as special")
Rel(person,reservations,"show/create/remove customer reservations, expired reservations")
Rel(person,rentals,"show/create/remove customer rentals, check out movie, calculate price,calculate penalty, not returned on time")
Rel(person,review,"show/create review")
Rel(review,points,"add points for review")
Rel(rentals,database,"reads/writes rentals")
Rel(rentals,points,"calculate points")
Rel(person,points,"show")
Rel(reservations,database,"reads/writes reservations")
Rel(movies,database,"reads data from movie catalogue db")
Rel(special,database,"reads/writes special")

}
Component(payments,"Payments","Facade/REST","Module responsible for payments realisation.")
Rel(rentals,payments,"<<SIGNAL>>send payment")

Component(information,"Email module","Facade/REST","Module responsible for end to end comunication (via email)")
Rel(rentals,information,"<<Signal>> send remind message")

@enduml